checks:
    php: true

filter:
    excluded_paths:
        - vendors/*
        - examples/*
        - tests/*
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=build/coverage_report'
                coverage:
                    file: 'build/coverage_report'
                    format: 'clover'