checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php: 7.4

            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: |
                            php -dxdebug.mode=coverage vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover