language: php

php:
  - 7.2
  - 7.3
  - 7.4

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - vendor/bin/phpunit --verbose